name: flutter_common_utilities
description: A Flutter utility package for common utils in Flutter App.
version: 0.1.13
homepage: https://github.com/SoftEngAliijaz/flutter_common_utilities

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg